apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector
  labels:
    app: sidecar-injector
data:
  sidecarconfig.yaml: |
    containers:
    - name: sidecar-nginx
      image: nginx:1.12.2
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: whatap
        mountPath: /opt/whatap

